<?php
namespace modava\categories\components;

use backend\components\MyController;

class MyCategoriesController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
