<?php
/**
 * Created by PhpStorm.
 * User: Kem Bi
 * Date: 12-Oct-18
 * Time: 11:53 AM
 */

namespace backend\modules\option\models;

class LangForm extends \yii\base\Model
{
    public $file;

    public $code;

    public function init()
    {
        if (file_exists($this->file)) {
            $this->code = file_get_contents($this->file);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['code'], 'required']
        ];
    }

    public function saveFile($content)
    {
        return file_put_contents($this->file, $content);
    }
}
