<?php
namespace modava\report\components;

use backend\components\MyController;

class MyReportController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
