<?php
namespace modava\products\components;

use backend\components\MyController;

class MyProductsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
