<?php
namespace modava\blogs\components;

use backend\components\MyController;

class MyBlogsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
