<?php

namespace modava\test;

use yii\base\Widget;

class Test extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('test', []);
    }
}
