<?php

namespace modava\iway\models\table;

use cheatsheet\Time;
use modava\iway\models\IwayTrayImages;
use modava\iway\models\query\IwayTrayQuery;
use Yii;
use yii\db\ActiveRecord;

class IwayTrayTable extends \yii\db\ActiveRecord
{
    const PHONG_KHAM_DE_XUAT = 0;
    const LABO_TIEP_NHAN = 1;
    const XU_LY_FILE = 2;
    const IN_3D = 3;
    const EP_KHAY = 4;
    const CAT_VIEN_KHAY = 5;
    const DONG_HOP = 6;
    const GIAO_PHONG_KHAM = 7;
    const PHONG_KHAM_NHAN = 8;
    const GIAO_KHACH_HANG = 9;
    const TAM_NGUNG = 10;
    const STATUS = [
        self::PHONG_KHAM_DE_XUAT => 'Phòng khám đề xuất',
        self::LABO_TIEP_NHAN => 'Labo tiếp nhận',
        self::XU_LY_FILE => 'Xử lý file in mẫu hàm',
        self::IN_3D => 'In 3D mẫu hàm',
        self::EP_KHAY => 'Ép khay',
        self::CAT_VIEN_KHAY => 'Cắt viền khay',
        self::DONG_HOP => 'Đóng hộp',
        self::GIAO_PHONG_KHAM => 'Bàn giao phòng khám',
        self::PHONG_KHAM_NHAN => 'Phòng khám nhận',
        self::GIAO_KHACH_HANG => 'Giao khách hàng',
        self::TAM_NGUNG => 'Tạm ngưng',
    ];

    const CHUA_DANH_GIA = 0;
    const CHUA_DAT = 1;
    const DAT = 2;
    const RESULT = [
        self::CHUA_DANH_GIA => 'Chưa đánh giá',
        self::CHUA_DAT => 'Chưa đạt',
        self::DAT => 'Đạt',
    ];

    public $_old_attributes = [];

    public static function tableName()
    {
        return 'iway_tray';
    }

    public static function find()
    {
        return new IwayTrayQuery(get_called_class());
    }

    public function afterFind()
    {
        $this->_old_attributes = $this->getOldAttributes();
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getCountImagesSuccess()
    {
        return $this->hasMany(IwayTrayImages::class, ['tray_id' => 'id'])->select(['type'])->andWhere([IwayTrayImages::tableName() . '.status' => IwayTrayImages::DAT])->groupBy('type')->count();
    }

    public function getCountImagesReject()
    {
        return $this->hasMany(IwayTrayImages::class, ['tray_id' => 'id'])->select(['type'])->andWhere([IwayTrayImages::tableName() . '.status' => IwayTrayImages::CHUA_DAT])->groupBy('type')->count();
    }
}
