<?php

namespace modava\iway\models\table;

use cheatsheet\Time;
use modava\iway\models\query\OrderQuery;
use Yii;
use yii\db\ActiveRecord;

class OrderTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'iway_order';
    }

    public static function find()
    {
        return new OrderQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getOrderUnFinishByCustomer($customer_id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-iway-order-table-get-order-un-finish-by-customer-' . $customer_id;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where([self::tableName() . '.customer_id' => $customer_id, self::tableName() . '.status' => self::STATUS_DISABLED]);
            $data = $query->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
