<?php
namespace modava\social\components;

use backend\components\MyController;

class MySocialController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
