<?php

namespace modava\iway\models;

use common\models\User;
use modava\iway\models\table\IwayTrayImagesTable;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;
use Yii;
use yii\web\UploadedFile;

class IwayTrayImages extends IwayTrayImagesTable
{
    const SCENARIO_SAVE = 'save';

    public $toastr_key = 'iway-tray-images';
    public $fileImage;
    public $fileImageBase64;

    public $uploadSuccess = [];

    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                [
                    'class' => AttributeBehavior::class,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_INSERT => ['created_at']
                    ],
                    'value' => time()
                ],
                [
                    'class' => AttributeBehavior::class,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_UPDATE => ['evaluate_at']
                    ],
                    'value' => function () {
                        if (is_array($this->_old_attributes) &&
                            array_key_exists('evaluate', $this->_old_attributes) &&
                            $this->_old_attributes['evaluate'] != $this->evaluate) return time();
                        return $this->evaluate_at;
                    }
                ],
                [
                    'class' => AttributeBehavior::class,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_UPDATE => ['evaluate_by']
                    ],
                    'value' => function () {
                        if (is_array($this->_old_attributes) &&
                            array_key_exists('evaluate', $this->_old_attributes) &&
                            $this->_old_attributes['evaluate'] != $this->evaluate) return Yii::$app->user->id;
                        return $this->evaluate_by;
                    }
                ],
                [
                    'class' => AttributeBehavior::class,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_VALIDATE => 'fileImage'
                    ],
                    'value' => function () {
                        return UploadedFile::getInstance($this, 'fileImage');
                    }
                ],
            ]
        );
    }

    public function beforeSave($insert)
    {
        if ($this->primaryKey == null && $this->fileImage != null) {
            $this->image = $this->uploadImage();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $save = parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        if ($save == false) {
            $this->deleteImage();
        }
        return $save;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fileImage'], 'required', 'on' => [self::SCENARIO_SAVE], 'when' => function () {
                return $this->primaryKey == null;
            }],
            [['tray_id', 'type'], 'required'],
            [['tray_id', 'type', 'status'], 'integer'],
            [['evaluate'], 'string'],
            [['fileImage'], 'file', 'extensions' => ['png', 'jpg', 'jpeg'], 'wrongExtension' => 'Chỉ chấp nhận định dạng: {extensions}'],
            [['type'], 'in', 'range' => array_keys(self::TYPE)],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'tray_id' => Yii::t('backend', 'Tray ID'),
            'image' => Yii::t('backend', 'Image'),
            'type' => Yii::t('backend', 'Type'),
            'status' => Yii::t('backend', 'Status'),
            'created_at' => Yii::t('backend', 'Created At'),
            'evaluate' => Yii::t('backend', 'Evaluate'),
            'evaluate_at' => Yii::t('backend', 'Evaluate At'),
            'evaluate_by' => Yii::t('backend', 'Evaluate By'),
        ];
    }

    private function uploadImage()
    {
        if (!$this->hasErrors() && $this->fileImage != null) {
            /* @var $image UploadedFile */
            $image = $this->fileImage;
            if ($image !== null) {
                $imageName = $image->baseName . '-' . time() . '.' . $image->extension;
                $pathImage = $this->pathUpload . $imageName;
                if (!$image->saveAs($pathImage)) {
                    $this->addError('image', 'Upload hình thất bại');
                    return false;
                }
                $this->uploadSuccess[] = $imageName;
                return $imageName;
            } else {
                $this->addError('image', 'Không có dữ liệu hình ảnh');
                return false;
            }
        }
    }

    private function deleteImage()
    {
        if ($this->uploadSuccess != null) {
            if (!is_array($this->uploadSuccess)) $this->uploadSuccess = [];
            foreach ($this->uploadSuccess as $uploadSuccess) {
                if (!is_dir($this->pathUpload . $uploadSuccess) && file_exists($this->pathUpload . $uploadSuccess)) {
                    @unlink($this->pathUpload . $uploadSuccess);
                }
            }
        }
    }
}
