<?php
namespace modava\iway\components;

use backend\components\MyController;

class MyIwayController extends MyController
{
    public function init()
    {
        // Set default TimeZone
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
