<?php

namespace modava\iway\components;

use backend\components\MyController;
use modava\iway\models\Order;
use Yii;
use yii\web\Response;


/**
 * @property MyIwayModel $model
 *
 */
class MyIwayController extends MyController
{
    public $model = null;

    public function init()
    {
        // Set default TimeZone
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionGetByKeyWord($q = null, $id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];

        if (!is_null($q)) {
            $out = $this->model::getByKeyWord($q);
        } elseif ($id > 0) {
            $record = $this->model::findOne($id);
            if ($record) {
                $out['results'] = ['id' => $id, 'text' => $record->title];
            }
        }
        return $out;
    }

    public function actionUpdateAjax($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = [
            'success' => true
        ];

        $model = $this->model::findOne($id);

        if (!$model) {
            $response['success'] = false;
            $response['error'] = ["Record {$id} not found!"];
        } else {
            $model->loadWithoutPrefix(Yii::$app->request->post());

            switch ($model->formName()) {
                case 'Order':
                    $model->scenario = Order::SCENARIO_NONE_LINE_ITEM;
                    break;
                default:
                    break;
            }

            if ($model->validate() && $model->save()) {
                $response['data'] = $model;
            } else {
                $response['success'] = false;
                $response['error'] = $model->getErrors();
            }
        }

        return $response;
    }
}
