<?php

namespace backend\modules\location\widgets;

use yii\base\Widget;

class LocationWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('locationWidget', [

        ]);
    }
}
