<?php

namespace modava\kenne\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class LogoTable extends \yii\db\ActiveRecord
{
    const ACTIVE_STATUS = 1;

    public static function tableName()
    {
        return 'logo';
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
