<?php

namespace modava\kenne\models\table;

use modava\kenne\models\Categories;
use Yii;
use yii\db\ActiveRecord;


class ProductsTable extends ActiveRecord
{
    public static function tableName()
    {
        return 'products';
    }

    public function getCategoryRelation(){
        return $this->hasOne(Categories::class,['id'=>"cat_id"]);
    }
    public function getCategory()
    {
        //return $this->hasOne(Categories::class,['cat_id'=>'id'])->orderBy('id');
        $categoryProduct = Categories::find()->all();
        return $categoryProduct;
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
