<?php
namespace modava\comment\components;

use backend\components\MyController;

class MyCommentController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
