<?php

namespace modava\affiliate\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class CouponTypeTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'coupon_type';
    }


    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getAll()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-coupon-type-get-all';
        $data = $cache->get($key);
        if (!$data) {
            $data = self::find()->all();
            $cache->set($key, $data, Time::SECONDS_IN_A_YEAR);
        }
        return $data;
    }
}
