<?php

namespace modava\affiliate\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class CouponTypeTable extends \yii\db\ActiveRecord
{
<<<<<<< HEAD
    public static function tableName()
    {
        return 'coupon_type';
=======
    const CACHE_KEY_GET_ALL = 'redis-affiliate-coupon-type-get-all';

    public static function tableName()
    {
        return 'affiliate_coupon_type';
>>>>>>> master
    }


    public function afterDelete()
    {
        $cache = Yii::$app->cache;
<<<<<<< HEAD
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
=======
        $keys = [
            self::CACHE_KEY_GET_ALL
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete();
>>>>>>> master
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
<<<<<<< HEAD
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getAll()
    {
        $cache = Yii::$app->cache;
        $key = 'redis-coupon-type-get-all';
        $data = $cache->get($key);
        if ($data === false) {
            $data = self::find()->all();
            $cache->set($key, $data, Time::SECONDS_IN_A_YEAR);
=======
        $keys = [
            self::CACHE_KEY_GET_ALL
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes);
    }

    public static function getAllRecords()
    {
        $cache = Yii::$app->cache;
        $data = $cache->get(self::CACHE_KEY_GET_ALL);
        if (!$data) {
            $data = self::find()->all();
            $cache->set(self::CACHE_KEY_GET_ALL, $data, Time::SECONDS_IN_A_YEAR);
>>>>>>> master
        }
        return $data;
    }
}
