<?php

namespace modava\affiliate\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class CouponTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
<<<<<<< HEAD
        return 'coupon';
=======
        return 'affiliate_coupon';
>>>>>>> master
    }


    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
<<<<<<< HEAD
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
=======
        return parent::beforeDelete();
>>>>>>> master
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
<<<<<<< HEAD
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
=======
        parent::afterSave($insert, $changedAttributes);
    }

    public static function getAll() {
        return self::find()->all();
>>>>>>> master
    }
}
