<?php
/* @var $generator yii\gii\generators\crud\Generator */
?>
<?= "<?php" ?>

namespace modava\<?= $generator->messageCategory ?>\widgets;

class NavbarWidgets extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('navbarWidgets', []);
    }
}