<?php
namespace modava\affiliate\widgets;

class JsCreateModalWidget extends \yii\base\Widget
{
    public $formClassName;
    public $modelName;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('jsCreateModalWidget', [
            'formClassName' => $this->formClassName,
            'modelName' => $this->modelName,
        ]);
    }
}