<?php
namespace modava\settings\components;

use backend\components\MyController;

class MySettingsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
