<?php
/* @var $generator yii\gii\generators\model\Generator */
?>
<?= "<?php" ?>

namespace modava\<?= $generator->moduleID ?>\components;

use backend\components\MyController;

class My<?= ucfirst($generator->moduleID) ?>Controller extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
