<?php
namespace modava\transactions\components;

use backend\components\MyController;

class MyTransactionsController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
