<?php

namespace backend\models\search;

use backend\models\phongkham\QuanlyModel;
use backend\modules\clinic\models\Clinic;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use backend\modules\user\models\User;

/**
 * Dep365CustomerOnlineSearch represents the model behind the search form of `backend\modules\customer\models\Dep365CustomerOnline`.
 */
class QuanlySearch extends QuanlyModel
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['district', 'co_so', 'permission_user'], 'integer'],
            [['name', 'phone', 'customer_code', 'sex', 'birthday', 'time_lichhen', 'full_name'], 'safe'],
            [['button', 'from', 'to'], 'string'],
        ];
    }

    public function scenarios()
    {
        return Model::scenarios();
    }


    public function search($params)
    {
        $user = new User();
        $roleUser = $user->getRoleName(\Yii::$app->user->id);

        $query = Clinic::find()->where(['dep365_customer_online.status' => Clinic::STATUS_DH, 'dep365_customer_online.dat_hen' => self::DA_DEN]);

        if ($roleUser == User::USER_DIRECT_SALE) {
            $query->andFilterWhere(['dep365_customer_online.directsale' => \Yii::$app->user->id]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);

        $this->load($params);

        if ($this->button == '') {
            $this->from = date('d-m-Y');
            $this->to = date('d-m-Y');
        }

        if ($this->button == '2' && $roleUser == User::USER_DIRECT_SALE) {
            $rowUser = User::findIdentity(\Yii::$app->user->id);
            $this->co_so = $rowUser->permission_coso;
        }

        $query->joinWith(['provinceHasOne']);

        if (!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'co_so' => $this->co_so,
//            'phone' => $this->phone,
        ]);

        $query->andFilterWhere(['like', 'full_name', $this->full_name]);
        $query->andFilterWhere(['like', 'customer_code', $this->customer_code]);
        if (isset($this->from) && isset($this->to) && $this->from != null && $this->to != null) {
            $from = strtotime($this->from);
            $to = strtotime($this->to) + 86399;
//            $query->andFilterWhere(['between', 'customer_come', $from, $to]);
            $query->andFilterWhere(['>', 'customer_come', $from]);
            $query->andFilterWhere(['<', 'customer_come', $to]);
        }

        return $dataProvider;
    }
}
