<?php

namespace modava\iway\controllers;

use backend\components\MyComponent;
use modava\iway\models\form\FormTrayImages;
use modava\iway\models\IwayImages;
use modava\iway\models\IwayTray;
use yii\db\Exception;
use Yii;
use yii\helpers\Html;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use backend\components\MyController;
use modava\iway\models\IwayTrayImages;
use modava\iway\models\search\IwayTrayImagesSearch;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

/**
 * IwayTrayImagesController implements the CRUD actions for IwayTrayImages model.
 */
class IwayTrayImagesController extends IwayImagesController
{
    public function init()
    {
        $this->parent_table = IwayTray::tableName();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\web\Response
     */
    public function actionIndex()
    {
        return $this->redirect(['iway/iway-tray/index']);
    }

    /**
     * Displays a single IwayTrayImages model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $tray = IwayTray::findOne(['id' => $id]);
        if ($tray == null) return $this->redirect(['/iway/iway-tray/index']);
        $query = IwayImages::find()
            ->where([
                'parent_table' => $this->parent_table,
                'parent_id' => $id,
            ])
            ->orderBy([IwayImages::tableName() . '.created_at' => SORT_ASC])
            ->indexBy('type');
        $tray_images = $query->all();
        $model = new IwayImages([
            'parent_table' => $this->parent_table,
            'parent_id' => $id
        ]);
        return $this->render('view', [
            'tray' => $tray,
            'model' => $model,
            'tray_images' => $tray_images
        ]);
    }
}
