<?php

namespace modava\location\models\table;

use cheatsheet\Time;
use modava\location\models\query\LocationCountryQuery;
use Yii;
use yii\db\ActiveRecord;

class LocationCountryTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'location_country';
    }

    public static function find()
    {
        return new LocationCountryQuery(get_called_class());
    }

    public function afterDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
