<?php
namespace modava\marketing\components;

use backend\components\MyController;

class MyMarketingController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
