<?php


namespace backend\widgets;

use yii\base\Widget;

class CallCenterWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $call_center_config = [];
        return $this->render('callCenterWidget', [
            'call_center_config' => json_encode($call_center_config)
        ]);
    }
}