<?php

namespace backend\widgets;

use yii\base\Widget;

class FooterWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('footerWidget', []);
    }
}
