<?php

namespace backend\widgets;

use backend\modules\general\models\Dep365Notification;
use yii\base\Widget;

class HeaderWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('headerWidget', []);
    }
}
