<?php

namespace modava\social\models\table;

use cheatsheet\Time;
use cornernote\linkall\LinkAllBehavior;
use modava\social\models\query\SocialOriginQuery;
use modava\social\models\SocialAgency;
use Yii;
use yii\db\ActiveRecord;

class SocialOriginTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'social_origin';
    }

    public static function find()
    {
        return new SocialOriginQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'social-agency-get-all-agency-' . $this->language,
            'social-agency-get-by-id-' . $this->id . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'social-agency-get-all-agency-' . $this->language,
            'social-agency-get-by-id-' . $this->id . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getAgencyHasMany()
    {
        return $this->hasMany(SocialAgencyTable::class, ['id' => 'agency_id'])
            ->viaTable('social_agency_origin_hasmany', ['origin_id' => 'id']);
    }

    public static function getAllOrigin($lang = 'vi')
    {
        $cache = Yii::$app->cache;
        $key = 'social-origin-get-all-origin-' . $lang;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find();
            if ($lang !== null) $query->where(['language' => $lang]);
            $data = $query->all();
        }
        return $data;
    }

    public static function getById($id = null, $lang = 'vi')
    {
        $cache = Yii::$app->cache;
        $key = 'social-agency-get-by-id-' . $id . '-' . $lang;
        $data = $cache->get($key);
        if ($data == false) {
            $query = self::find()->where(['id' => $id])->published();
            if ($lang !== null) $query->andWhere(['language' => $lang]);
            $data = $query->one();
            $cache->set($key, $data);
        }
        return $data;
    }
}
