<?php

namespace modava\social\models\table;

use cheatsheet\Time;
use modava\social\models\query\SocialFanpageQuery;
use Yii;
use yii\db\ActiveRecord;

class SocialFanpageTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'social_fanpage';
    }

    public static function find()
    {
        return new SocialFanpageQuery(get_called_class());
    }

    public function getOriginHasOne()
    {
        return $this->hasOne(SocialOriginTable::class, ['id' => 'origin_id']);
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
