<?php

namespace backend\modules\general\controllers;

use backend\modules\user\models\User;
use Yii;
use backend\modules\general\models\Dep365Notification;
use backend\modules\general\models\search\Dep365NotificationSearch;
use backend\components\MyController;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\components\MyComponent;
use yii\web\Response;

/**
 * NotificationController implements the CRUD actions for Dep365Notification model.
 */
class NotificationController extends MyController
{
    public function init()
    {
        $date = date('d-m-Y');
        $from = strtotime($date);
        $to = $from + 86399;

        $cache = \Yii::$app->cache;
        $key = 'redis-header-get-notification-miss-' . $from . '-' . $to;
        $cache->delete($key);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new Dep365NotificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (MyComponent::hasCookies('pageSize')) {
            $dataProvider->pagination->pageSize = MyComponent::getCookies('pageSize');
        } else {
            $dataProvider->pagination->pageSize = 20;
        }
        $pageSize = $dataProvider->pagination->pageSize;
        $totalCount = $dataProvider->totalCount;
        $totalPage = (($totalCount + $pageSize - 1) / $pageSize);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'totalPage' => $totalPage,
        ]);
    }

    public function actionPerpage($perpage)
    {
        MyComponent::setCookies('pageSize', $perpage);
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->request->isAjax && $model != null) {
            if (is_array($model->users)) {
                $model->users = ArrayHelper::map($model->users, 'id', 'id');
            } else {
                $model->users = [];
            }
            if (!in_array(Yii::$app->user->id, $model->users)) {
                $model->users[Yii::$app->user->id] = Yii::$app->user->id;
                try {
                    $model->save();
                } catch (Exception $ex) {
                }
            }
            return $this->renderAjax('view', [
                'model' => $model
            ]);
        }
    }

    public function actionCreate()
    {
        if (Yii::$app->request->isAjax) {
            $model = new Dep365Notification();

            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                Yii::$app->response->format = Response::FORMAT_JSON;

                try {
                    $model->is_bg = '3';
                    $model->save();
                    return [
                        'status' => 200,
                        'mess' => Yii::$app->params['create-success'],
                    ];
                } catch (\yii\db\Exception $exception) {
                    return [
                        'status' => 400,
                        'mess' => Yii::$app->params['create-danger'],
                        'error' => $exception,
                    ];
                }
            }

            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Dep365Notification model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->request->isAjax) {
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;

                if ($model->validate()) {
                    try {
                        $model->save();
                        return [
                            'status' => 200,
                            'mess' => Yii::$app->params['update-success'],
                        ];
                    } catch (\yii\db\Exception $exception) {
                        return [
                            'status' => 400,
                            'mess' => Yii::$app->params['update-danger'],
                            'error' => $exception,
                        ];
                    }
                } else {
                    $err = '';
                    foreach ($model->getErrors() as $error) {
                        $err .= $error . '<br>';
                    }

                    return [
                        'status' => 400,
                        'mess' => $err
                    ];
                }
            }

            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            $id = Yii::$app->request->post('id');
            try {
                if ($this->findModel($id)->delete()) {
                    return [
                        "status" => "success"
                    ];
                } else {
                    return [
                        "status" => "failure"
                    ];
                }
            } catch (\yii\db\Exception $e) {
                return [
                    "status" => "exception"
                ];
            }
        }

        return $this->redirect(['index']);
    }

    public function actionShowHide()
    {
        if (Yii::$app->request->isAjax) {
            $id = Yii::$app->request->post('id');

            $model = $this->findModel($id);
            try {
                if ($model->status == 1) {
                    $model->status = 0;
                } else {
                    $model->status = 1;
                }
                if ($model->save()) {
                    echo 1;
                }
            } catch (\yii\db\Exception $exception) {
                echo 0;
            }
        }
    }

    public function actionDeleteMultiple()
    {
        try {
            $action = Yii::$app->request->post('action');
            $selectCheckbox = Yii::$app->request->post('selection');
            if ($action === 'c') {
                if ($selectCheckbox) {
                    foreach ($selectCheckbox as $id) {
                        $this->findModel($id)->delete();
                    }
                    \Yii::$app->session->setFlash('indexFlash', 'Bạn đã xóa thành công.');
                }
            }
        } catch (\yii\db\Exception $e) {
            if ($e->errorInfo[1] == 1451) {
                throw new \yii\web\HttpException(400, 'Failed to delete the object.');
            } else {
                throw $e;
            }
        }
        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        $model = Dep365Notification::findOne($id);
        /*$user = new User();
        $userInfo = $user->getCoso(Yii::$app->user->id);
        if ($model != null && $userInfo != null && $userInfo->subroleHasOne != null && $model->for_who != Dep365Notification::FOR_EVERYONE && $model->for_who != $userInfo->subroleHasOne->role) {
            $model = null;
        }*/
        if ($model !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
