<?php

namespace backend\modules\option\widgets;

use yii\base\Widget;

class OptionWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('optionWidget', [

        ]);
    }
}
