<?php
namespace modava\orders\components;

use backend\components\MyController;

class MyOrdersController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
