<?php

namespace backend\modules\helper\models\search;

use backend\modules\helper\models\SearchFaceCustomer;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class FbSearch extends SearchFaceCustomer
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    public function search($params)
    {
        $query = self::find()->where('face_customer not like "facebook"');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            //Không hiển thị dữ liệu khi textinput không thỏa rules
            $query->where('0=1');
            return $dataProvider;
        }
        $query->andFilterWhere(['or',
            ['like', 'name', $this->name],
            ['like', 'forename', $this->name],
            ['like', 'full_name', $this->name],
            ['like', 'customer_code', $this->name],
            ['like', 'phone', $this->name],
            ['like', 'birthday', $this->name],
            ['like', 'note', $this->name],
        ]);

        return $dataProvider;
    }
}
