<?php

namespace backend\modules\helper\models\search;

use backend\modules\helper\models\SendSmsCustomer;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class SendSmsSearch extends SendSmsCustomer
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function scenarios()
    {
        return Model::scenarios();
    }

    public function search($params)
    {
        $query = self::find();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        $query->andFilterWhere(['or',
            ['like', 'name', $this->name],
            ['like', 'forename', $this->name],
            ['like', 'full_name', $this->name],
            ['like', 'customer_code', $this->name],
            ['like', 'phone', $this->name],
            ['like', 'birthday', $this->name],
            ['like', 'note', $this->name],
        ]);

        return $dataProvider;
    }
}
