<?php

namespace modava\customer\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class CustomerOrderDetailTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'customer_order_detail';
    }


    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getById($id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-customer-order-detail-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where([self::tableName() . '.id' => $id])->one();
            $cache->set($key, $data);
        }
        return $data;
    }
}
