<?php


namespace frontend\widgets;


use common\components\Component;
use yii\base\Widget;

class AlertWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $data = unserialize(serialize(Component::getCookies('cart')));

        return $this->render('alertWidget',[
            'data'=>$data
        ]);
    }
}