<?php
namespace modava\test\components;

use backend\components\MyController;

class MyTestController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
