<?php

namespace modava\log\controllers;

use modava\log\components\MyLogController;

class Voip24hLogController extends MyLogController
{
    public function init()
    {
        /* If don't have class CallCenter => redirect to index */
        if (!class_exists('\modava\voip24h\CallCenter')) return $this->redirect(['/site/index']);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index', []);
    }
}