<?php

namespace modava\products\models\table;

use modava\categories\models\Categories;
use Yii;
use yii\db\ActiveRecord;

class ProductsTable extends ActiveRecord
{
    const ACTIVE_STATUS = 1;
    const DISABLE_STATUS = 0;

    public static function tableName()
    {
        return 'products';
    }

    public $pathImage;

    public function getImage()
    {
        if ($this->pro_image == null || is_dir($this->pathImage . '/' . $this->pro_image) || !file_exists($this->pathImage . '/' . $this->pro_image)) return null;
        return Yii::$app->assetManager->publish($this->pathImage . '/' . $this->pro_image)[1];
    }

    /*public static function tableName()
    {
        return 'products';
    }*/

    public function getCategory()
    {
        //return $this->hasOne(Categories::class,['cat_id'=>'id'])->orderBy('id');
        $categoryProduct = Categories::find()->all();
        return $categoryProduct;
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
