<?php

namespace modava\products\models\table;

use cheatsheet\Time;
use modava\categories\models\Categories;
use Yii;
use yii\db\ActiveRecord;

class ProductsTable extends \yii\db\ActiveRecord
{
    public $pathImage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->pathImage = Yii::getAlias('@frontend/web/uploads/folder');
    }

    public function getImage()
    {
        if ($this->image == null || is_dir($this->pathImage . '/' . $this->image) || !file_exists($this->pathImage . '/' . $this->image)) return null;
        return Yii::$app->assetManager->publish($this->pathImage . '/' . $this->image)[1];
    }

    public static function tableName()
    {
        return 'products';
    }

    public function getCategory()
    {
        //return $this->hasOne(Categories::class,['cat_id'=>'id'])->orderBy('id');
        $categoryProduct = Categories::find()->all();
        return $categoryProduct;
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
