<?php
/**
 * Created by PhpStorm.
 * User: Kem Bi
 * Date: 26-May-18
 * Time: 12:10 PM
 */

namespace backend\components;

use backend\modules\user\models\User;
use yii\web\Controller;
use Yii;

class MyController extends Controller
{
    public function init()
    {
        parent::init();
        $user = new User();
        $userRoleName = $user->getRoleName(Yii::$app->user->id);
        $this->view->params['userRoleName'] = $userRoleName;
//        if (Yii::$app->user->id != null) {
//            $system_maintenance = Setting::getKey('system_maintenance');
//            if ($system_maintenance != null && $system_maintenance->value == '1') {
//                if (!Yii::$app->user->can(User::USER_DEVELOP)) {
//                    return $this->redirect(['/bao-tri']);
//                }
//            }
//        }
//        MyComponent::setCookies('id', Yii::$app->user->id);
    }

//    public function __construct(string $id, Module $module, array $config = [])
//    {
//        if (!Yii::$app->user->isGuest && !Yii::$app->authManager->checkAccess(Yii::$app->user->id, 'loginToBackend')) {
//            $cookie_user_login = MyComponent::getCookies('dashboard-365dep-user-login');
//            if ($cookie_user_login !== false) {
//                $cookie_user_login = (int)$cookie_user_login;
//            }
//            $user_login = User::find()->where(['id' => $cookie_user_login, 'status' => User::STATUS_ACTIVE])->one();
//            Yii::$app->user->logout();
//            if ($user_login != null) {
//                MyComponent::setCookies('dashboard-365dep-user-login', null, time() - 3600);
//                Yii::$app->user->login($user_login, Time::SECONDS_IN_A_MONTH);
//            }
//        }
//        parent::__construct($id, $module, $config);
//    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function goBack($defaultUrl = null)
    {
        return Yii::$app->getResponse()->redirect(Yii::$app->getUser()->getReturnUrl($defaultUrl));
    }
}
