<?php
namespace modava\kenne\components;

use backend\components\MyController;

class MyKenneController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
