<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '\'{class}\' phải mở rộng từ \'yii\\rbac\\Rule\' hoặc lớp con',
    'Action' => 'Hành động',
    'Are you sure to delete this item?' => 'Bạn có chắc chắn muốn xóa mục này?',
    'Assign' => 'Chỉ định',
    'Assignment : {0}' => 'Assignment : {0}',
    'Assignments' => 'Assignment',

    'Create' => 'Tạo mới',
    'Create Rule' => 'Tạo Rule',
    'Create Role' => 'Tạo Role',

    'Delete' => 'Xóa',
    'Invalid rule "{value}"' => 'Quy tắc không hợp lệ "{value}"',
    'Item has been removed.' => 'Mục đã bị xóa.',
    'Item has been saved.' => 'Mục đã được lưu.',

    'Permissions' => 'Permission',
    'Refresh' => 'Làm mới',
    'Remove' => 'Di chuyển',
    'Roles' => 'Role',
    'Role : {0}' => 'Role : {0}',
    'Permission : {0}' => 'Permission : {0}',
    'Create Permission' => 'Tạo Permission',
    'Routes' => 'Route',
    'Rule' => 'Rule',
    'Rule "{value}" does not exists' => 'Rule "{value}" không tồn tại',
    'Rule : {0}' => 'Rule : {0}',

    'Rule has been deleted.' => 'Rule đã bị xóa.',
    'Rule has been saved.' => 'Rule đã được lưu.',
    'Rules' => 'Rule',
    'Search for assigned' => 'Tìm kiếm được chỉ định',
    'Search for available' => 'Tìm kiếm có sẵn',
    'The requested page does not exist.' => 'Trang được yêu cầu không tồn tại.',
    'Type' => 'Loại',
    'Unknown class \'{class}\'' => 'Lớp không xác định \'{class}\'',
    'Update' => 'Cập nhật',
    'Update Rule : {0}' => 'Rule cập nhật : {0}',
    'Update Role : {0}' => 'Role cập nhật : {0}',
    'Update Permission : {0}' => 'Cập nhật Permission : {0}',
    'Select Rule' => 'Chọn Rule',
    'User' => 'Thành viên',
    'Widget' => 'Tiện ích',
    'Roles Routes' => 'Role Route',

    /* =========== Auth Item Model  =============*/
    'Name'=>'Tên',
    'Description'=>'Mô tả',
    'Rule Name'=>'Tên Rule',
    'Data'=>'Data',
    'Rule not exists'=>'Rule không tồn tại',


       /* =========== Rule Manager  =============*/
    /* 1. Rule Model */

    'Class Name'=>'Tên class',// Rule Model
    'Class "{className}" not exist'=>'Class "{className}" không tồn tại',
    'Class "{className}" must extends yii\rbac\Rule'=>'Class "{className}" cần phải extends yii\rbac\Rule',
    'The "{className}::\$name" is not set'=>'Biến "{className}::\$name" chưa được khai báo hoặc nó bằng null',
    'The "{className}::\$name" is incorrect with the name of rule you have set'=>'Biến "{className}::\$name" không đúng với rule name mà bạn muốn tạo',


     /* 2. Rule Views */
    'Rules Manager' => 'Quản lý các rule',


    /* =========== Permisstion Manager  =============*/
    /* 1. Permisstion Model */
    'Permission name'=>'Tên permistion',

    /* 2. Permisstion Views */
    'Permisstions Manager'=>'Quản lý các permission',


    /* =========== Permisstion Manager  =============*/
    /* 1. Permisstion Model */
    'Role name'=>'Tên role',

    /* 2. Permisstion Views */
    'Roles Manager'=>'Quản lý các role',
    /* =========== User role assignemnt  =============*/
    /* 1. Permisstion Views */
    'User Assignment'=>'Phân quyền người dùng',
    'Assignment'=>'Phân quyền',
];
